config/routes.rb
Rails.application.routes.draw do
  resources :stations
  
  root to: "pages#home"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :companies do
  resources :stations
  end
  post '/bsktreq', to: 'petitions#recbaskt'
  get '/reqtkn', to: 'csrf_tokens#show'
  resources :orders, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :stations
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :station
  validates :table, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :company
  has_many :order
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :companies
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:show, :index]
    include Pundit::Authorization
  
    # Pundit: allow-list approach
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  
    # Uncomment when you *really understand* Pundit!
    # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    # def user_not_authorized
    #   flash[:alert] = "You are not authorized to perform this action."
    #   redirect_to(root_path)
    # end
    def after_sign_in_path_for(user)
      companies_path(current_user)
    end
  
    def after_sign_up_path_for(user)
      companies_path(current_user)
    end

    private
  
    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_station, only: [:show]
  def index
    @companies = policy_scope(Company)
  end

  def show
    authorize @company
    @stations = Station.where(company: @company)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_station
    @company = Company.find(params[:id])
  end
end

app/controllers/csrf_tokens_controller.rb
class CsrfTokensController < ApplicationController
    skip_before_action :authenticate_user!, only: :show
    def show
        skip_authorization
        csrf_token = form_authenticity_token
        render json: { csrf_token: csrf_token }
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    skip_authorization
    orders = session[:orders]
    orders.each do |order|
      order["content"] = format_order_content(order["content"])
      create(order)
    end
    session.delete(:orders)
    if current_user.present?
      sign_out(current_user)
    end
  end

  def create(order)
    new_order = Order.new(order)
    if new_order.save
      ActionCable.server.broadcast(
        "order_#{new_order.station_id}",
        { 
          action: "created"
        }
      )
    end
  end

  def delete
  end

  private
   
  def format_order_content(content)
    str = ""
    content.each do |item|
      str += "• #{item["quantity"]}x #{item["name"]} €#{item["price"]}\n"
    end
    str
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home]
  def home
  end
end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :recbaskt
  skip_before_action :authenticate_user!, only: :recbaskt

  def recbaskt
      skip_authorization
      @basket_params = JSON.parse(request.body.read)
      login
  end

  private

  def login
    #----------------- Login User ------------------#
    user = User.find_by(email: @basket_params["email"])
    if user && user.valid_password?(@basket_params["password"])
      sign_in(user)
    end
    create_order
  end

  def create_order
    orders = []
    company_name = @basket_params["company"]
    table = @basket_params["table"]
    total = @basket_params["total"]
    items = @basket_params["items"]

    company = Company.find_by(name: company_name)
    stations = Station.where(company_id: company)
    
    if stations.length > 1
      stations.each do |station|
        acumulator = 0.00
        order = {
          table: table,
          content: [],
          total: total,
          number: 1,
          station_id: station["id"]
        }

        items.each do |item| 
          if station["name"] == item["station"]
            order[:content] << item
            acumulator += item["price"] * item["quantity"]
          end
        end
        if order[:content].size > 0
          order[:total] = acumulator
          orders << order
        end
      end
      session[:orders] = orders
      redirect_to new_order_path
    end
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: %i[ show edit update destroy ]

  # GET /stations or /stations.json
  def index
    @stations = policy_scope(Station)
  end

  # GET /stations/1 or /stations/1.json
  def show
    @orders = Order.where(station_id: @station)
    authorize @station
  end

  # GET /stations/new
  def new
    @station = Station.new
    @company_id = params[:company_id]
    authorize @station
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations or /stations.json
  def create
    @station = Station.new(station_params)
    authorize @station
    if @station.save
      flash[:success] = "Resource was successfully created."
      redirect_to company_path(@station.company_id)
    else
      render 'new'
    end
  end

  # PATCH/PUT /stations/1 or /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to station_url(@station), notice: "Station was successfully updated." }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1 or /stations/1.json
  def destroy
    @station.destroy

    respond_to do |format|
      format.html { redirect_to stations_url, notice: "Station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def station_params
      params.require(:station).permit(:name, :company_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def update
      user_params
      user = User.find(@user[:user_id])
      authorize user
      user.update({:active => @user[:active], :role_id => @user[:role]})
      redirect_to companies_path(current_user)
    end
  
    private
  
    def user_params
      @user = params.require(:user).permit(:active, :role, :user_id)
      if @user[:role] == "master"
        @user[:role] = 1
      elsif @user[:role] == "manager"
        @user[:role] = 2
      elsif @user[:role] == "visitor"
        @user[:role] = 2
      end
    end
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<h1>Hola</h1>
<% @companies.each do |company| %>
    <%= button_to "#{company.name}",  company_path(company), method: :get, class:"cmp-index-btn-lgt" %>
<% end %>

<%= button_to " LOG OUT ",  destroy_user_session_path, method: :delete, class:"cmp-index-btn-lgt" %>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>
<h1><%= @company.name %></h1>
<br>
<h3>Stations</h3>

<div id="stations">
  <% @stations.each do |station| %>
    <%= link_to "#{ station.name }", station_path(station) %>
  <% end %>
</div>

<%= link_to "New station", new_station_path(company_id: @company.id) %>
<%= @company.id %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarOrder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </body>
</html>

app/views/pages/_welcome.html.erb
<h3>WELCOME</h3>
<p>If you're looking for an easy and efficient way to showcase your gastronomic offer to your customers, you've come to the right place.
Our service allows you to create an online menu for your restaurant, with all the dishes, drinks, and desserts you offer, along with their prices and descriptions. In addition, our system allows you to edit the menu in real time, so you can easily add new items or modify existing ones.</p>
    

app/views/pages/home.html.erb
<div class="h-container">
  <div class = "h-btns-txt">
    <%= render partial: "welcome" %>
    <div class = "h-btns-div">
      <%= button_to " Login ", new_user_session_path, class: "h-btn", method: :get %>
      <%= button_to " Sign up ", new_user_registration_path, class:"h-btn", method: :get %>
    </div>
  </div>
</div>

app/views/stations/_orders.html.erb
<div class="row">
  <% @orders.each do |order|  %>
    <div  class="stn-show-order-list col-sm-6 col-md-4 col-xl-2">
      <div class="stn-show-order-list-top">
        <h5>Table #: <%= order.table %></h5>
        <p><%= order.created_at %></p>
      </div>
      <hr>
      <p class="stn-show-order-list-content"><%= raw order.content.gsub("\n", "<br>") %></p>
      <div class="stn-show-order-list-total">
        <hr>
        <p>Total : <%= order.total %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render "form", station: @station %>

<br>

<div>
  <%= link_to "Show this station", @station %> |
  <%= link_to "Back to stations", stations_path %>
</div>

app/views/stations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stations</h1>

<div id="stations">
  <% @stations.each do |station| %>
    <%= station %>
    <p>
      <%= link_to "Show this station", station %>
    </p>
  <% end %>
</div>

<%= link_to "New station", new_station_path %>

app/views/stations/new.html.erb
<div class="ssn-new-container">
  <div class="ssn-new-content">
    <h2>New station</h2>
    <%= simple_form_for(@station) do |f| %>
      <div class="form-inputs ssn-new-form-inputs">
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.input :name,
                  as: :string,
                  input_html: { autocomplete: "off" },
                  label: "Station Name" %>
        <%= f.hidden_field :company_id, value:  @company_id %>
      </div>

      <div class="form-action">
        <%= f.button :submit %>
      </div>
    <% end %>
    <div>
      <%= link_to "Back to stations", stations_path %>
      <%= @company_id %>
    </div>
  </div>
</div>

app/views/stations/show.html.erb
<div class="stn-sw-container">
  <h2><%= @station.name %></h2>
  <div class="stn-sw-orders">
    <%= render partial: 'orders'%>
  </div>
  <div>
    <%= link_to "Edit this station", edit_station_path(@station) %> |
    <%= link_to "Back to stations", stations_path %>

    <%= button_to "Destroy this station", @station, method: :delete %>
  </div>
</div>
<div data-controller="websocket-order" data-stationid="<%= @station.id %>"></div>